services:
  - type: web
    name: movie-booking
    runtime: python
    rootDir: homework2/movie_theater_booking

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn movie_theater_booking.wsgi:application --bind 0.0.0.0:$PORT

    # Run migrations on each deploy
    preDeployCommand: python manage.py migrate

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: movie_theater_booking.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: movie-booking-db
          property: connectionString

    plan: free
    autoDeploy: true

databases:
  - name: movie-booking-db
    plan: free
